### ISSUE TITLE
Εικόνες από την εγκατάσταση και τον αισθητήρα

### ISSUE THREAD

**Issue by goodvibrations32** [hmu-mech-npap/diss.tn.doc#5]
Καποια στιγμή θα ήθελα να ανέβω στο εργαστήριο για φωτογραφίες. Δεν είναι επήγον απλά για να βάλω στο κείμενο καναδυό.

**Comment by goodvibrations32** [comment]
@npapnet λεω να μην χρησιμοποιήσω εικόνες από την εγκατάσταση του εργαστηρίου... Το κείμενο έχει τελειώσει και είναι έτοιμο να το δείτε....
Όποτε θέλετε μπορούμε να τα πούμε και από κοντά γιατί κατέβηκα για εξεταστική.

**Comment by npapnet** [comment]
OK Niko,
  όλο λέω να σου στείλω να σου πω να τα πούμε...
  Αυτό βασικα που θέλω να σου πω είναι να προχωρήσεις να το κλείσεις, γιατί
βρίσκομαι στην ασυνήθιστη κατάσταση να προχωράς γρηγορότερα από ότι εγώ.
Και δυστυχώς δεν έχω χρόνο να κάνω catch up. Επίσης φοβάμαι ότι αν κάνω
catch up μετά ο επόμενος πτυχιακάριος θα ερθει και δεν θα δω ούτε το 1% της
απόδοσης σου οπότε δεν ξέρω αν είναι καλή ιδέα να προσπαθήσω.

Ν

**Comment by goodvibrations32** [comment]
μπορούμε να κάνουμε μια συνάντηση μέσα στη βδομάδα για το κείμενο και βλέπουμε πως προχωράμε. Για το paper θελέτε να κάνω κάτι? Ευελπιστώ να τελειώσω με τα μαθήματα την τρέχουσα εξεταστική και θα έχω χρόνο να ασχοληθώ.

**Comment by npapnet** [comment]
Nikola,
   to paper, έκατσα και το τελείωσα γιατί μας έστειλαν μήνυμα να το
κλείσουμε μέσα σε 15 ημέρες. Δεν σε ενοχλησα γιατί δεν είχε νοήμα.
   Αν θες να περάσεις την Πέμπτη το πρωί είναι η καλύτερη ημέρα.

Ν.

**Comment by goodvibrations32** [comment]
γράφω 11-13:00... Μπορείτε πριν ή μετά;;

**Comment by goodvibrations32** [comment]
κλείνω αυτό αφού ολοκληρόνουμε το κομμάτι του κειμένου χωρίς να χρειάζονται οι φωτογραφίες από το εργαστήριο
