### ISSUE TITLE
bibliography (the chapters problem)

### ISSUE THREAD

**Issue by goodvibrations32** [hmu-mech-npap/diss.tn.doc#9]
Βλέποντας τις διορθώσεις που προτείνατε για την βιβλιογραφία, θεωρώ και εγώ πως φαίνεται κάπως άσχημο με τα ξεχωριστά κεφάλαια και παρατήρησα το εξής:

- Το sciencedirecet από όπου πήρα τα αρχεία `.bib` για τα 2 αυτά βιβλία προσφέρουν την βιβλιογραφία ανά κεφάλαιο και όχι ξεχωριστά.
  - μπορώ να βάλω στην βιβλιογραφία το indexing ή τα περιεχόμενα του κάθε βιβλίου αλλά δεν μπορώ να βρώ ένα reference για όλο το βιβλίο μαζί. Και αυτή η λύση μου φαίνεται λίγο «τεμπέλικη».

- Αν ξέρετε κάποιο site που μπορώ να βγάλω το reference από το doi ή κάποιο αντίστοιχο μοναδικό αριθμό θα το εκτιμούσα. 
 

Τι επιλογή μου δίνει 
-----
### Τα αρχεία `.bib` locally
![maim-region-20230710-122449](https://github.com/hmu-mech-npap/diss.tn.doc/assets/87814811/b174bd17-9e24-4de1-919f-c61e15639341)
### Η επιλογή στο site sciencedirect.com για το ένα βιβλίο (Εdmund Lai)
![maim-region-20230710-123645](https://github.com/hmu-mech-npap/diss.tn.doc/assets/87814811/d58fbda8-1d39-4426-addd-cf4092d3d291)

**Comment by goodvibrations32** [comment]
found the solution as we said

**Comment by npapnet** [comment]
Niko,
   Τώρα το είδα.
   δεν είναι συνηθισμένο. Και νομίζω ότι υπάρχει λόγος. Σε μια πτυχιακή
συνήθως η βιβλιογραφική έρευνα είναι συγκεντρωμένη σε ένα ή δύο το πολύ
κεφάλαια. Οπότε, αυτό που καταλήγεις είναι ότι πάλι σε ένα κεφάλαιο έχεις
βιβλιογραφία και επιπλέον υπάρχει περίπτωση να εμφανιστεί δυο φορές η ίδια
βιβλιογραφική αναφορά σε επόμενο κεφάλαιο.
     αυτό που προτείνεις είναι συνηθισμένο σε βιβλία που έχουν διακριτα
κεφάλαια με διαφορετικό αντικείμενο με διαφορετικούς συγγραφείς.

Ν.

**Comment by goodvibrations32** [comment]
Έφτιαξα καινούρια entries για να μπορέσω να βάλω το βιβλίο ολόκληρο.

Εδώ η πρώτη βιβλιογραφία είναι custom από ένα βιβλίο που μου τα έβγαζε σε κεφάλαια. Νομίζω είναι η καλύτερη λύση..

https://github.com/hmu-mech-npap/diss.tn.doc/blob/c1bec0558d1845f10260954fbbcfa6a7f0918791/diss-docs/main_doc/diss_bibliography.bib#L1-L11

**Comment by goodvibrations32** [comment]
Καλημέρα, βρήκα τρόπο να χρησιμοποιήσω **IEEE** style για την βιβλιογραφία μόνο που έχω ένα θέμα στο indentation...
![image](https://github.com/hmu-mech-npap/diss.tn.doc/assets/87814811/a6cd6625-ad01-40e6-bc67-528ca968f799)
από την δεύτερη αναφορά και μετά έχω άλλο indentation...
εμένα δεν με ενοχλεί..και έτσι φαίνεται μέσα στο κείμενό μου.
![image](https://github.com/hmu-mech-npap/diss.tn.doc/assets/87814811/c4d9e603-3c2c-4ac2-b621-164477e9aa99)

Αν συμφωνείτε και εσείς μπορούμε να το κλείσουμε αυτό.(τα doi + links δεν θα είναι magenta..θα τα κάνω και αυτά μαύρα στο preamble.)

**Comment by npapnet** [comment]
Ναι Νίκο. Μια χαρά είναι.
